const languageOptions = [
  { label: 'Afrikaans 🇿🇦', value: 'af' },
  { label: 'Amharic 🇪🇹', value: 'am' },
  { label: 'Arabic 🇸🇦', value: 'ar' },
  { label: 'Assamese 🇮🇳', value: 'as' },
  { label: 'Azerbaijani 🇦🇿', value: 'az' },
  { label: 'Bangla 🇧🇩', value: 'bn' },
  { label: 'Bosnian 🇧🇦', value: 'bs' },
  { label: 'Bulgarian 🇧🇬', value: 'bg' },
  { label: 'Catalan 🇪🇸', value: 'ca' },
  { label: 'Chinese (Simplified) 🇨🇳', value: 'zh-Hans' },
  { label: 'Chinese (Traditional) 🇹🇼', value: 'zh-Hant' },
  { label: 'Croatian 🇭🇷', value: 'hr' },
  { label: 'Czech 🇨🇿', value: 'cs' },
  { label: 'Danish 🇩🇰', value: 'da' },
  { label: 'Dutch 🇳🇱', value: 'nl' },
  { label: 'English 🇺🇸', value: 'en' },
  { label: 'Estonian 🇪🇪', value: 'et' },
  { label: 'Finnish 🇫🇮', value: 'fi' },
  { label: 'French 🇫🇷', value: 'fr' },
  { label: 'Georgian 🇬🇪', value: 'ka' },
  { label: 'German 🇩🇪', value: 'de' },
  { label: 'Greek 🇬🇷', value: 'el' },
  { label: 'Gujarati 🇮🇳', value: 'gu' },
  { label: 'Haitian Creole 🇭🇹', value: 'ht' },
  { label: 'Hebrew 🇮🇱', value: 'he' },
  { label: 'Hindi 🇮🇳', value: 'hi' },
  { label: 'Hungarian 🇭🇺', value: 'hu' },
  { label: 'Icelandic 🇮🇸', value: 'is' },
  { label: 'Indonesian 🇮🇩', value: 'id' },
  { label: 'Irish 🇮🇪', value: 'ga' },
  { label: 'Italian 🇮🇹', value: 'it' },
  { label: 'Japanese 🇯🇵', value: 'ja' },
  { label: 'Javanese 🇮🇩', value: 'jv' },
  { label: 'Kannada 🇮🇳', value: 'kn' },
  { label: 'Kazakh 🇰🇿', value: 'kk' },
  { label: 'Khmer 🇰🇭', value: 'km' },
  { label: 'Korean 🇰🇷', value: 'ko' },
  { label: 'Lao 🇱🇦', value: 'lo' },
  { label: 'Latvian 🇱🇻', value: 'lv' },
  { label: 'Lithuanian 🇱🇹', value: 'lt' },
  { label: 'Macedonian 🇲🇰', value: 'mk' },
  { label: 'Malay 🇲🇾', value: 'ms' },
  { label: 'Malayalam 🇮🇳', value: 'ml' },
  { label: 'Maltese 🇲🇹', value: 'mt' },
  { label: 'Marathi 🇮🇳', value: 'mr' },
  { label: 'Mongolian 🇲🇳', value: 'mn' },
  { label: 'Myanmar (Burmese) 🇲🇲', value: 'my' },
  { label: 'Nepali 🇳🇵', value: 'ne' },
  { label: 'Norwegian (Bokmål) 🇳🇴', value: 'nb' },
  { label: 'Odia 🇮🇳', value: 'or' },
  { label: 'Pashto 🇦🇫', value: 'ps' },
  { label: 'Persian 🇮🇷', value: 'fa' },
  { label: 'Polish 🇵🇱', value: 'pl' },
  { label: 'Portuguese (Brazil, Portugal) 🇵🇹', value: 'pt' },
  { label: 'Punjabi 🇮🇳', value: 'pa' },
  { label: 'Romanian 🇷🇴', value: 'ro' },
  { label: 'Russian 🇷🇺', value: 'ru' },
  { label: 'Sindhi 🇵🇰', value: 'sd' },
  { label: 'Sinhala 🇱🇰', value: 'si' },
  { label: 'Slovak 🇸🇰', value: 'sk' },
  { label: 'Slovenian 🇸🇮', value: 'sl' },
  { label: 'Somali 🇸🇴', value: 'so' },
  { label: 'Spanish 🇪🇸', value: 'es' },
  { label: 'Swahili 🇰🇪', value: 'sw' },
  { label: 'Swedish 🇸🇪', value: 'sv' },
  { label: 'Tamil 🇮🇳', value: 'ta' },
  { label: 'Telugu 🇮🇳', value: 'te' },
  { label: 'Thai 🇹🇭', value: 'th' },
  { label: 'Tibetan 🇨🇳', value: 'bo' },
  { label: 'Tigrinya 🇪🇷', value: 'ti' },
  { label: 'Turkish 🇹🇷', value: 'tr' },
  { label: 'Ukrainian 🇺🇦', value: 'uk' },
  { label: 'Urdu 🇵🇰', value: 'ur' },
  { label: 'Uzbek 🇺🇿', value: 'uz' },
  { label: 'Vietnamese 🇻🇳', value: 'vi' },
  { label: 'Welsh 🏴', value: 'cy' },
  { label: 'Xhosa 🇿🇦', value: 'xh' },
  { label: 'Yiddish 🇮🇱', value: 'yi' },
  { label: 'Zulu 🇿🇦', value: 'zu' }
];

export default languageOptions;